# starship config by BTY

[directory]
style = '#f5c2e7'

[username]
show_always = true
style_user = '#cba6f7'

[character]
success_symbol = '[\$](#a6e3a1)'
error_symbol = '[\$](#f38ba8)'

[memory_usage]
disabled = false
threshold = -1
style = '#94e2d5'
symbol = '[î°™ ](#94e2d5)'

[git_branch]
symbol = 'ï˜ '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count} "
behind = "ğŸ¢ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
untracked = "ğŸ›¤ï¸ Ã—${count} "
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
staged = "ğŸ—ƒï¸  Ã—${count} "
renamed = "ğŸ“› Ã—${count} "
deleted = "ğŸ—‘ï¸  Ã—${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[java]
symbol = 'î¶¯ '
